version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./src:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php
  php:
    build: ./images/php
    volumes:
      - ./src:/var/www
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
